// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalAIAgent.Core.Data;

#nullable disable

namespace PersonalAIAgent.Core.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260909184955_InitialSqliteCreate")]
    partial class InitialSqliteCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PersonalAIAgent.Core.Data.API", b =>
                {
                    b.Property<int>("APIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("APIString")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("APIId");

                    b.ToTable("APIs");
                });
#pragma warning restore 612, 618
        }
    }
}
